name: Bandit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout Bandit
        uses: actions/checkout@v4
        with:
          repository: 'ericwb/bandit'
          ref: 'sarif'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install .[sarif]
          rm -rf bandit

      - name: Checkout local repository
        uses: actions/checkout@v4

      - name: Run Precli
        run: bandit -r . -f sarif -o results.sarif || true

      - uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
