name: Precaution

on:
  workflow_dispatch:

jobs:
  analyze:
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Perform Precaution Analysis
        uses: securesauce/precli-action@v1
