name: Precaution

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Analyze
        uses: securesauce/precli-actionv@0.1.0
        with: 
          path: "."
